List<String> challengesList = [
  'Do 20 Push-Ups NOW',
  'Meditate for 5 Minutes',
  'Write 100 Words',
  'Eat No Sweets Just For Today',
  'Do a Plank for 1 Minute Straight',
  'Learn a New Word Today',
  "Don't Complain Today",
  'Your Daily Screen Time For Today is 1 Hour',
  'Read 500 Words Today',
  'Write Something Down You are Grateful For',
  'Learn a New Skill Today',
  'Stretch for 3 Minutes Today',
  'Make Some Money Today',
  'Today You Have To Take a Cold Shower',
  'Wake Up 30 Minutes Earlier Tomorrow',
  'Drink the Recommended Amount of Water Today',
  'Give a Sincere Compliment to Someone',
];
